import { describe, expect, it, vi } from "vitest";

import { createComposer, createWorkflow, type Workflow } from "../internal";
import { WorkflowBatchError, WorkflowStepError } from "../internal/errors";
import { mockLogger, mockTracer } from "./observability-mocks";
import { createTestStep, noOpContextProvider, type TestBag } from "./test-utils";

type WorkflowFailureLog = {
  duration: number;
  error: {
    name: string;
    message: string;
  };
  failureContext: {
    stepName?: string;
    stepNumber?: number;
    batchNumber: number;
    stepStartTime?: number;
    stepDuration?: number;
  };
  bagState?: unknown;
};

function firstWorkflowFailureLog(): WorkflowFailureLog {
  const metadata = vi.mocked(mockLogger.error).mock.calls[0]?.[1];
  expect(metadata).toBeDefined();
  return metadata as unknown as WorkflowFailureLog;
}

// Mock @opentelemetry/api so trace.getTracer() returns our mockTracer
vi.mock("@opentelemetry/api", async (importOriginal) => {
  const actual = await importOriginal<typeof import("@opentelemetry/api")>();
  const mocks =
    await vi.importActual<typeof import("./observability-mocks")>("./observability-mocks");
  const mockTrace = Object.create(actual.trace);
  mockTrace.getTracer = () => mocks.mockTracer;
  return { ...actual, trace: mockTrace };
});

// Mock defaults so createDefaultMetrics() returns our mockMetrics
vi.mock("../internal/defaults", async (importOriginal) => {
  const actual = await importOriginal<typeof import("../internal/defaults")>();
  const mocks =
    await vi.importActual<typeof import("./observability-mocks")>("./observability-mocks");
  return { ...actual, createDefaultMetrics: () => mocks.mockMetrics };
});

/**
 * Composer with mock logger for asserting on log calls in tests.
 */
const composerWithMockLogger = createComposer({
  contextProvider: noOpContextProvider,
  logger: mockLogger,
});

describe("Observability Error Logging", () => {
  describe("Execution Context Tracking", () => {
    it("should track step name and number correctly during execution", async () => {
      const step1 = createTestStep("step1", ["input"], ["processed"], (bag) => ({
        processed: bag.input.toUpperCase(),
      }));
      const step2 = createTestStep("step2", ["processed"], ["result"], (bag) => ({
        result: `${bag.processed}!`,
      }));

      const workflow = createWorkflow<TestBag>("test-workflow")
        .requires("input")
        .build([step1, step2]);

      try {
        await composerWithMockLogger.runSyncWorkflow(workflow, { input: "test" });
      } catch (_error) {
        // This workflow should not throw, but we catch for safety
      }

      // Verify that the logger was called with the correct context for the last step
      // We expect the info log for successful completion to contain the final context
      expect(mockLogger.info).toHaveBeenCalledWith(
        "Workflow completed successfully",
        expect.objectContaining({
          workflowName: "test-workflow",
          workflowId: expect.any(String), // Generated by runWorkflow
          outputFields: expect.arrayContaining(["input", "processed", "result"]),
        }),
      );
    });

    it("should track batch number correctly for parallel steps", async () => {
      const step1 = createTestStep("step1", ["input"], ["processed"], (bag) => ({
        processed: bag.input.toUpperCase(),
      }));
      const step2 = createTestStep("step2", ["input"], ["doubled"], (bag) => ({
        doubled: bag.input + bag.input,
      }));
      const step3 = createTestStep("step3", ["processed", "doubled"], ["result"], (bag) => ({
        result: `${bag.processed}-${bag.doubled}`,
      }));

      const workflow = createWorkflow<TestBag>("parallel-workflow")
        .requires("input")
        .build([step1, step2, step3]);

      try {
        await composerWithMockLogger.runSyncWorkflow(workflow, { input: "test" });
      } catch (_error) {
        // This workflow should not throw
      }

      // Verify that batch numbers were correctly tracked in spans
      expect(mockTracer.startSpan).toHaveBeenCalledWith(
        "workflow.parallel-workflow.batch.1",
        expect.objectContaining({
          attributes: expect.objectContaining({
            "workflow.batch.number": 1,
            "workflow.batch.steps.names": expect.stringMatching(/(step1,step2|step2,step1)/),
          }),
        }),
        expect.anything(), // Context parameter
      );
      expect(mockTracer.startSpan).toHaveBeenCalledWith(
        "workflow.parallel-workflow.batch.2",
        expect.objectContaining({
          attributes: expect.objectContaining({
            "workflow.batch.number": 2,
            "workflow.batch.steps.names": "step3",
          }),
        }),
        expect.anything(), // Context parameter
      );
    });

    it("should track step start time during execution", async () => {
      vi.useFakeTimers();
      vi.setSystemTime(new Date("2024-01-01T00:00:00Z"));
      try {
        const slowStep = createTestStep("slowStep", ["input"], ["processed"], async (_bag) => {
          // Simulate some processing time
          await new Promise((resolve) => setTimeout(resolve, 10));
          throw new Error("Slow step failed");
        });

        const workflow = createWorkflow<TestBag>("test-workflow")
          .requires("input")
          .build([slowStep]);

        const workflowPromise = composerWithMockLogger.runSyncWorkflow(workflow, { input: "test" });
        await vi.runAllTimersAsync();
        const { error } = await workflowPromise;
        expect(error).toBeInstanceOf(WorkflowBatchError);

        const logCall = firstWorkflowFailureLog();
        // stepStartTime might not be available in failureContext, check if it exists
        if (logCall.failureContext.stepStartTime) {
          expect(logCall.failureContext.stepDuration).toBeCloseTo(0.01, 2); // ~10ms ±5ms
        }
      } finally {
        vi.useRealTimers();
      }
    });
  });

  describe("Error Log Content", () => {
    it("should include complete failure context for step errors", async () => {
      const failingStep = createTestStep("failingStep", ["input"], ["processed"], () => {
        throw new Error("Processing failed");
      });

      const workflow = createWorkflow<TestBag>("test-workflow")
        .requires("input")
        .build([failingStep]);

      const { error } = await composerWithMockLogger.runSyncWorkflow(workflow, { input: "test" });
      expect(error).toBeInstanceOf(WorkflowBatchError);

      expect(mockLogger.error).toHaveBeenCalledWith(
        "Workflow execution failed",
        expect.objectContaining({
          workflowName: "test-workflow",
          workflowId: expect.any(String), // Generated by runWorkflow
          duration: expect.any(Number),
          error: {
            name: "WorkflowBatchError",
            message: expect.stringContaining("failingStep"),
            stack: expect.any(String),
          },
          bagState: expect.any(Object), // Now includes bagState for debugging
          failureContext: expect.objectContaining({
            stepName: "failingStep",
            stepNumber: 1,
            totalSteps: 1,
            batchNumber: 1,
          }),
        }),
      );
    });

    it("should exclude step duration for validation errors", async () => {
      // Create a workflow with missing dependencies to trigger validation error
      const step1 = createTestStep("step1", ["result"], ["processed"], (bag) => ({
        processed: bag.result.toUpperCase(),
      }));

      const workflow = {
        name: "test-workflow",
        steps: [step1],
      } as unknown as Workflow<TestBag>;

      try {
        await composerWithMockLogger.runSyncWorkflow(workflow, { input: "test" }); // Missing 'result'
        throw new Error("Expected workflow to throw a validation error");
      } catch (_error) {
        // Validation errors should not include step duration
        const logCall = firstWorkflowFailureLog();
        expect(logCall.failureContext.stepDuration).toBeUndefined();
        expect(logCall.failureContext.stepName).toBeUndefined();
        expect(logCall.failureContext.stepNumber).toBeUndefined();
      }
    });

    it("should include bag state when debug logging enabled", async () => {
      const failingStep = createTestStep("failingStep", ["input"], ["processed"], () => {
        throw new Error("Processing failed");
      });

      const workflow = createWorkflow<TestBag>("test-workflow")
        .requires("input")
        .build([failingStep]);

      const { error } = await composerWithMockLogger.runSyncWorkflow(workflow, { input: "test" });
      expect(error).toBeInstanceOf(WorkflowBatchError);

      const logCall = firstWorkflowFailureLog();
      expect(logCall.bagState).toEqual({ input: "test" });
    });
  });

  describe("Error Scenarios", () => {
    it("should log validation errors without step context", async () => {
      // Workflow with a step that needs 'result' but it's not provided
      const step1 = createTestStep("step1", ["result"], ["processed"], (bag) => ({
        processed: bag.result.toUpperCase(),
      }));
      const workflow = {
        name: "validation-error-workflow",
        steps: [step1],
      } as unknown as Workflow<TestBag>;

      try {
        await composerWithMockLogger.runSyncWorkflow(workflow, { input: "test" });
        throw new Error("Expected workflow to throw a validation error");
      } catch (_error) {
        const logCall = firstWorkflowFailureLog();
        expect(logCall.error.message).toContain(
          'requires field "result" but no previous step provides it',
        );
        expect(logCall.failureContext.stepName).toBeUndefined();
        expect(logCall.failureContext.batchNumber).toBe(0); // No batches started
      }
    });

    it("should log initial field overwrite errors without step context", async () => {
      const step1 = createTestStep("step1", ["input"], ["input"], (bag) => ({
        input: bag.input.toUpperCase(), // Trying to overwrite initial field!
      }));

      const workflow = {
        name: "overwrite-error-workflow",
        steps: [step1],
        requiredInitial: ["input"],
      } as unknown as Workflow<TestBag>;

      try {
        await composerWithMockLogger.runSyncWorkflow(workflow, { input: "test" });
        throw new Error("Expected workflow to throw an overwrite error");
      } catch (_error) {
        const logCall = firstWorkflowFailureLog();
        expect(logCall.error.message).toContain(
          'Step "step1" cannot overwrite initial field "input"',
        );
        expect(logCall.failureContext.stepName).toBeUndefined(); // Error before step execution
        expect(logCall.failureContext.batchNumber).toBe(0);
      }
    });

    it("should handle errors in parallel batch execution", async () => {
      const step1 = createTestStep("step1", ["input"], ["processed"], (bag) => ({
        processed: bag.input.toUpperCase(),
      }));
      const failingStep = createTestStep("failingStep", ["input"], ["doubled"], () => {
        throw new Error("Parallel step failed");
      });
      const step3 = createTestStep("step3", ["processed", "doubled"], ["result"], (bag) => ({
        result: `${bag.processed}-${bag.doubled}`,
      }));

      const workflow = createWorkflow<TestBag>("parallel-error-workflow")
        .requires("input")
        .build([step1, failingStep, step3]);

      const { error } = await composerWithMockLogger.runSyncWorkflow(workflow, { input: "test" });
      expect(error).toBeInstanceOf(WorkflowBatchError);

      const logCall = firstWorkflowFailureLog();
      expect(logCall.error.message).toContain("failingStep");
      expect(logCall.failureContext.stepName).toBe("failingStep"); // The failing step
      expect(logCall.failureContext.batchNumber).toBe(1); // First batch
    });
  });

  describe("Error Propagation and Logging Hierarchy", () => {
    it("should only log at workflow level for step errors", async () => {
      const failingStep = createTestStep("failingStep", ["input"], ["processed"], () => {
        throw new Error("Step error for logging hierarchy");
      });
      const workflow = createWorkflow<TestBag>("hierarchy-workflow")
        .requires("input")
        .build([failingStep]);

      const { error } = await composerWithMockLogger.runSyncWorkflow(workflow, { input: "test" });
      expect(error).toBeInstanceOf(WorkflowBatchError);

      // Expect only one error log at the workflow level
      expect(mockLogger.error).toHaveBeenCalledTimes(1);
      expect(mockLogger.error).toHaveBeenCalledWith(
        "Workflow execution failed",
        expect.objectContaining({
          workflowName: "hierarchy-workflow",
          error: expect.objectContaining({
            message: expect.stringContaining("failingStep"),
          }),
        }),
      );
    });

    it("should preserve original error information", async () => {
      const originalError = new Error("Original error message");
      const failingStep = createTestStep("failingStep", ["input"], ["processed"], () => {
        throw originalError;
      });
      const workflow = createWorkflow<TestBag>("preserve-error-workflow")
        .requires("input")
        .build([failingStep]);

      const { error } = await composerWithMockLogger.runSyncWorkflow(workflow, { input: "test" });

      // With Promise.allSettled, errors are wrapped in WorkflowBatchError
      expect(error).toBeInstanceOf(WorkflowBatchError);
      const batchError = error as WorkflowBatchError;
      expect(batchError.errors).toHaveLength(1);

      // The original error is preserved inside the step error
      const stepError = batchError.errors[0]!;
      expect(stepError).toBeInstanceOf(WorkflowStepError);
      expect(stepError.message).toContain("Original error message");
      expect(stepError.originalError).toBe(originalError);
      expect(stepError.cause).toBe(originalError);

      const logCall = firstWorkflowFailureLog();
      // Logged error is the WorkflowBatchError
      expect(logCall.error.name).toBe("WorkflowBatchError");
      expect(logCall.error.message).toContain("failingStep");
    });

    it("should handle non-Error objects thrown from steps", async () => {
      const nonErrorObject = { code: 500, message: "Something went wrong" };
      const failingStep = createTestStep("failingStep", ["input"], ["processed"], () => {
        throw nonErrorObject;
      });
      const workflow = createWorkflow<TestBag>("non-error-workflow")
        .requires("input")
        .build([failingStep]);

      const { error } = await composerWithMockLogger.runSyncWorkflow(workflow, { input: "test" });

      // With Promise.allSettled, errors are wrapped in WorkflowBatchError
      expect(error).toBeInstanceOf(WorkflowBatchError);
      const batchError = error as WorkflowBatchError;
      expect(batchError.errors).toHaveLength(1);

      // Non-Error objects are wrapped in WorkflowStepError inside the batch
      const stepError = batchError.errors[0]!;
      expect(stepError).toBeInstanceOf(WorkflowStepError);
      expect(stepError.message).toContain("[object Object]");
      expect(stepError.originalError.message).toContain("[object Object]");

      const logCall = firstWorkflowFailureLog();
      expect(logCall.error.name).toBe("WorkflowBatchError");
      expect(logCall.error.message).toContain("failingStep");
    });
  });

  describe("Timing and Performance Context", () => {
    it("should include accurate workflow duration", async () => {
      vi.useFakeTimers();
      vi.setSystemTime(new Date("2024-01-01T00:00:00Z"));
      try {
        const slowStep = createTestStep("slowStep", ["input"], ["processed"], async (_bag) => {
          await new Promise((resolve) => setTimeout(resolve, 50)); // 50ms delay
          throw new Error("Slow step failed");
        });

        const workflow = createWorkflow<TestBag>("test-workflow")
          .requires("input")
          .build([slowStep]);

        const startTime = Date.now();
        const workflowPromise = composerWithMockLogger.runSyncWorkflow(workflow, { input: "test" });
        await vi.runAllTimersAsync();
        const { error } = await workflowPromise;
        expect(error).toBeInstanceOf(WorkflowBatchError);

        const endTime = Date.now();
        const actualDuration = (endTime - startTime) / 1000; // in seconds

        const logCall = firstWorkflowFailureLog();
        const loggedDuration = logCall.duration;

        expect(loggedDuration).toBeCloseTo(actualDuration, 1); // Within 100ms of actual
      } finally {
        vi.useRealTimers();
      }
    });

    it("should include step duration for step execution errors", async () => {
      vi.useFakeTimers();
      vi.setSystemTime(new Date("2024-01-01T00:00:00Z"));
      try {
        const timedStep = createTestStep("timedStep", ["input"], ["processed"], async (_bag) => {
          await new Promise((resolve) => setTimeout(resolve, 20)); // 20ms delay
          throw new Error("Timed step failed");
        });

        const workflow = createWorkflow<TestBag>("test-workflow")
          .requires("input")
          .build([timedStep]);

        const workflowPromise = composerWithMockLogger.runSyncWorkflow(workflow, { input: "test" });
        await vi.runAllTimersAsync();
        const { error } = await workflowPromise;
        expect(error).toBeInstanceOf(WorkflowBatchError);

        const logCall = firstWorkflowFailureLog();
        expect(logCall.failureContext.stepDuration).toBeCloseTo(0.02, 1); // ~20ms ±50ms
      } finally {
        vi.useRealTimers();
      }
    });
  });

  describe("Complex Workflow Error Scenarios", () => {
    it("should handle errors in multi-batch workflows", async () => {
      const step1 = createTestStep("step1", ["input"], ["processed"], (bag) => ({
        processed: bag.input.toUpperCase(),
      }));
      const step2 = createTestStep("step2", ["processed"], ["doubled"], (bag) => {
        if (bag.processed === "TEST") {
          throw new Error("Step2 failed intentionally");
        }
        return { doubled: bag.processed + bag.processed };
      });
      const step3 = createTestStep("step3", ["doubled"], ["result"], (bag) => ({
        result: `${bag.doubled}!`,
      }));

      const workflow = createWorkflow<TestBag>("multi-batch-workflow")
        .requires("input")
        .build([step1, step2, step3]);

      const { error } = await composerWithMockLogger.runSyncWorkflow(workflow, { input: "test" });
      expect(error).toBeInstanceOf(WorkflowBatchError);

      const logCall = firstWorkflowFailureLog();
      expect(logCall.error.message).toContain("step2");
      expect(logCall.failureContext.stepName).toBe("step2");
      expect(logCall.failureContext.stepNumber).toBe(2);
      expect(logCall.failureContext.batchNumber).toBe(2); // Step2 is in batch 2
    });

    it("should handle errors with complex bag state", async () => {
      const step1 = createTestStep("step1", ["input"], ["processed"], (bag) => ({
        processed: bag.input.toUpperCase(),
      }));
      const step2 = createTestStep("step2", ["processed"], ["count"], (bag) => {
        if (bag.processed.length > 4) {
          // "HELLO" is 5 chars, so this will trigger
          throw new Error("Input too long");
        }
        return { count: bag.processed.length };
      });
      const step3 = createTestStep("step3", ["processed", "count"], ["result"], () => {
        throw new Error("Complex step failed");
      });

      const workflow = createWorkflow<TestBag>("complex-workflow")
        .requires("input")
        .build([step1, step2, step3]);

      const { error } = await composerWithMockLogger.runSyncWorkflow(workflow, { input: "hello" });
      expect(error).toBeInstanceOf(WorkflowBatchError);

      const logCall = firstWorkflowFailureLog();
      expect(logCall.error.message).toContain("step2");
      expect(logCall.failureContext.stepName).toBe("step2");
      expect(logCall.bagState).toEqual({ input: "hello", processed: "HELLO" }); // Bag state at failure
    });
  });

  describe("Multiple Error Scenarios", () => {
    it("should handle logger failures during error logging", async () => {
      // Make the logger throw when logging errors
      mockLogger.error.mockImplementation(() => {
        throw new Error("Error logging failed");
      });

      const failingStep = createTestStep("failingStep", ["input"], ["processed"], () => {
        throw new Error("Step execution failed");
      });

      const workflow = createWorkflow<TestBag>("multiple-errors-workflow")
        .requires("input")
        .build([failingStep]);

      // The logging error will be thrown during cleanup since it happens after the step error is caught
      await expect(
        composerWithMockLogger.runSyncWorkflow(workflow, { input: "test" }),
      ).rejects.toThrow("Error logging failed");

      expect(mockLogger.error).toHaveBeenCalled();

      // Reset the mock for other tests
      mockLogger.error.mockImplementation(() => {});
    });
  });

  describe("Async Step Error Handling", () => {
    it("should handle errors in async step cleanup", async () => {
      vi.useFakeTimers();
      try {
        const asyncFailingStep = createTestStep(
          "asyncFailingStep",
          ["input"],
          ["processed"],
          async () => {
            // Simulate async work then fail
            await new Promise((resolve) => setTimeout(resolve, 5));
            throw new Error("Async step failed");
          },
        );

        const workflow = createWorkflow<TestBag>("async-error-workflow")
          .requires("input")
          .build([asyncFailingStep]);

        // With Promise.allSettled, errors are wrapped in WorkflowBatchError
        const workflowPromise = composerWithMockLogger.runSyncWorkflow(workflow, { input: "test" });
        await vi.runAllTimersAsync();
        const { error } = await workflowPromise;
        expect(error).toBeInstanceOf(WorkflowBatchError);

        // Should still log the error properly
        expect(mockLogger.error).toHaveBeenCalledWith(
          "Workflow execution failed",
          expect.objectContaining({
            error: expect.objectContaining({
              message: expect.stringContaining("asyncFailingStep"),
            }),
          }),
        );
      } finally {
        vi.useRealTimers();
      }
    });
  });
});
