import { describe, expect, it, vi } from "vitest";

import { createComposer, createWorkflow } from "../internal";
import { createMockSpan, mockLogger, mockMetrics, mockTracer } from "./observability-mocks";
import { createTestStep, noOpContextProvider, type TestBag } from "./test-utils";

// Mock @opentelemetry/api so trace.getTracer() returns our mockTracer
vi.mock("@opentelemetry/api", async (importOriginal) => {
  const actual = await importOriginal<typeof import("@opentelemetry/api")>();
  const mocks =
    await vi.importActual<typeof import("./observability-mocks")>("./observability-mocks");
  const mockTrace = Object.create(actual.trace);
  mockTrace.getTracer = () => mocks.mockTracer;
  return { ...actual, trace: mockTrace };
});

// Mock defaults so createDefaultMetrics() returns our mockMetrics
vi.mock("../internal/defaults", async (importOriginal) => {
  const actual = await importOriginal<typeof import("../internal/defaults")>();
  const mocks =
    await vi.importActual<typeof import("./observability-mocks")>("./observability-mocks");
  return { ...actual, createDefaultMetrics: () => mocks.mockMetrics };
});

/**
 * Composer with mock logger for asserting on log calls in e2e tests.
 */
const composerWithMockLogger = createComposer({
  contextProvider: noOpContextProvider,
  logger: mockLogger,
});

describe("Observability End-to-End Component Tests", () => {
  describe("Success Path Observability", () => {
    it("should create complete observability trace for successful single-step workflow", async () => {
      const step1 = createTestStep("processInput", ["input"], ["processed"], (bag) => ({
        processed: bag.input.toUpperCase(),
      }));

      const workflow = createWorkflow<TestBag>("success-workflow").requires("input").build([step1]);

      const { bag } = await composerWithMockLogger.runSyncWorkflow(workflow, { input: "hello" });

      // Verify workflow execution succeeded
      expect(bag).toEqual({ input: "hello", processed: "HELLO" });

      // Verify complete observability chain
      // 1. Workflow span created
      expect(mockTracer.startSpan).toHaveBeenCalledWith(
        "workflow.success-workflow",
        expect.objectContaining({
          attributes: expect.objectContaining({
            "workflow.name": "success-workflow",
            "workflow.id": expect.any(String), // Generated by runWorkflow
            "workflow.steps.count": 1,
            "workflow.initial.fields": "input",
          }),
        }),
      );

      // 2. Batch span created
      expect(mockTracer.startSpan).toHaveBeenCalledWith(
        "workflow.success-workflow.batch.1",
        expect.objectContaining({
          attributes: expect.objectContaining({
            "workflow.name": "success-workflow",
            "workflow.batch.number": 1,
            "workflow.batch.steps.count": 1,
            "workflow.batch.steps.names": "processInput",
          }),
        }),
        expect.anything(), // Context parameter
      );

      // 3. Step span created
      expect(mockTracer.startSpan).toHaveBeenCalledWith(
        "workflow.success-workflow.step.processInput",
        expect.objectContaining({
          attributes: expect.objectContaining({
            "workflow.name": "success-workflow",
            "workflow.batch.number": 1,
            "step.name": "processInput",
            "step.needs": "input",
            "step.provides": "processed",
          }),
        }),
        expect.anything(), // Context parameter
      );

      // 4. Success metrics recorded
      expect(mockMetrics.counter).toHaveBeenCalledWith(
        "workflow_executions_total",
        "Total number of workflow executions",
      );
      expect(mockMetrics.histogram).toHaveBeenCalledWith(
        "workflow_duration_seconds",
        "Duration of workflow executions in seconds",
      );

      // 5. Success log created
      expect(mockLogger.info).toHaveBeenCalledWith(
        "Workflow completed successfully",
        expect.objectContaining({
          workflowName: "success-workflow",
          workflowId: expect.any(String), // Generated by runWorkflow
          duration: expect.any(Number),
          batchCount: 1,
          outputFields: ["input", "processed"],
        }),
      );
    });

    it("should create complete observability trace for successful multi-batch workflow", async () => {
      const step1 = createTestStep("processInput", ["input"], ["processed"], (bag) => ({
        processed: bag.input.toUpperCase(),
      }));
      const step2 = createTestStep("addCount", ["processed"], ["count"], (bag) => ({
        count: bag.processed.length,
      }));
      const step3 = createTestStep("createResult", ["processed", "count"], ["result"], (bag) => ({
        result: `${bag.processed} (${bag.count} chars)`,
      }));

      const workflow = createWorkflow<TestBag>("multi-batch-workflow")
        .requires("input")
        .build([step1, step2, step3]);

      const { bag } = await composerWithMockLogger.runSyncWorkflow(workflow, { input: "hello" });

      // Verify workflow execution succeeded
      expect(bag).toEqual({
        input: "hello",
        processed: "HELLO",
        count: 5,
        result: "HELLO (5 chars)",
      });

      // Verify workflow-level observability
      expect(mockTracer.startSpan).toHaveBeenCalledWith(
        "workflow.multi-batch-workflow",
        expect.objectContaining({
          attributes: expect.objectContaining({
            "workflow.name": "multi-batch-workflow",
            "workflow.id": expect.any(String), // Generated by runWorkflow
            "workflow.steps.count": 3,
            "workflow.initial.fields": "input",
          }),
        }),
      );

      // Verify all three batches were created
      expect(mockTracer.startSpan).toHaveBeenCalledWith(
        "workflow.multi-batch-workflow.batch.1",
        expect.objectContaining({
          attributes: expect.objectContaining({
            "workflow.batch.number": 1,
            "workflow.batch.steps.names": "processInput",
          }),
        }),
        expect.anything(), // Context parameter
      );

      expect(mockTracer.startSpan).toHaveBeenCalledWith(
        "workflow.multi-batch-workflow.batch.2",
        expect.objectContaining({
          attributes: expect.objectContaining({
            "workflow.batch.number": 2,
            "workflow.batch.steps.names": "addCount",
          }),
        }),
        expect.anything(), // Context parameter
      );

      expect(mockTracer.startSpan).toHaveBeenCalledWith(
        "workflow.multi-batch-workflow.batch.3",
        expect.objectContaining({
          attributes: expect.objectContaining({
            "workflow.batch.number": 3,
            "workflow.batch.steps.names": "createResult",
          }),
        }),
        expect.anything(), // Context parameter
      );

      // Verify all three steps were traced
      expect(mockTracer.startSpan).toHaveBeenCalledWith(
        "workflow.multi-batch-workflow.step.processInput",
        expect.any(Object),
        expect.anything(), // Context parameter
      );
      expect(mockTracer.startSpan).toHaveBeenCalledWith(
        "workflow.multi-batch-workflow.step.addCount",
        expect.any(Object),
        expect.anything(), // Context parameter
      );
      expect(mockTracer.startSpan).toHaveBeenCalledWith(
        "workflow.multi-batch-workflow.step.createResult",
        expect.any(Object),
        expect.anything(), // Context parameter
      );

      // Verify success log with correct batch count
      expect(mockLogger.info).toHaveBeenCalledWith(
        "Workflow completed successfully",
        expect.objectContaining({
          workflowName: "multi-batch-workflow",
          batchCount: 3,
          outputFields: ["input", "processed", "count", "result"],
        }),
      );
    });

    it("should create complete observability trace for successful parallel workflow", async () => {
      const step1 = createTestStep("processInput", ["input"], ["processed"], (bag) => ({
        processed: bag.input.toUpperCase(),
      }));
      const step2 = createTestStep("doubleInput", ["input"], ["doubled"], (bag) => ({
        doubled: bag.input + bag.input,
      }));
      const step3 = createTestStep(
        "combineResults",
        ["processed", "doubled"],
        ["result"],
        (bag) => ({
          result: `${bag.processed} + ${bag.doubled}`,
        }),
      );

      const workflow = createWorkflow<TestBag>("parallel-workflow")
        .requires("input")
        .build([step1, step2, step3]);

      const { bag } = await composerWithMockLogger.runSyncWorkflow(workflow, { input: "hi" });

      // Verify workflow execution succeeded
      expect(bag).toEqual({
        input: "hi",
        processed: "HI",
        doubled: "hihi",
        result: "HI + hihi",
      });

      // Verify parallel batch (batch 1) contains both parallel steps
      expect(mockTracer.startSpan).toHaveBeenCalledWith(
        "workflow.parallel-workflow.batch.1",
        expect.objectContaining({
          attributes: expect.objectContaining({
            "workflow.name": "parallel-workflow",
            "workflow.batch.number": 1,
            "workflow.batch.steps.count": 2,
            "workflow.batch.steps.names": expect.stringMatching(
              /(processInput,doubleInput|doubleInput,processInput)/,
            ),
          }),
        }),
        expect.anything(), // Context parameter
      );

      // Verify sequential batch (batch 2) contains the combining step
      expect(mockTracer.startSpan).toHaveBeenCalledWith(
        "workflow.parallel-workflow.batch.2",
        expect.objectContaining({
          attributes: expect.objectContaining({
            "workflow.name": "parallel-workflow",
            "workflow.batch.number": 2,
            "workflow.batch.steps.count": 1,
            "workflow.batch.steps.names": "combineResults",
          }),
        }),
        expect.anything(), // Context parameter
      );

      // Verify batch size metrics for parallel execution
      expect(mockMetrics.histogram).toHaveBeenCalledWith(
        "batch_size",
        "Number of steps executed in parallel batches",
      );
    });
  });

  describe("Complete Span Hierarchy Verification", () => {
    it("should create proper span hierarchy with correct relationships", async () => {
      const spans: Array<ReturnType<typeof createMockSpan>> = [];
      vi.mocked(mockTracer.startSpan).mockImplementation(() => {
        const span = createMockSpan();
        spans.push(span);
        return span;
      });

      const step1 = createTestStep("parentStep", ["input"], ["processed"], (bag) => ({
        processed: bag.input.toUpperCase(),
      }));

      const workflow = createWorkflow<TestBag>("hierarchy-test-workflow")
        .requires("input")
        .build([step1]);

      await composerWithMockLogger.runSyncWorkflow(workflow, { input: "test" });

      // Verify spans are created in correct order (parent to child)
      const spanCalls = vi.mocked(mockTracer.startSpan).mock.calls;

      // Find the workflow, batch, and step span calls
      const workflowSpanCall = spanCalls.find(([name]: [string]) =>
        name.includes("workflow.hierarchy-test-workflow"),
      );
      const batchSpanCall = spanCalls.find(([name]: [string]) =>
        name.includes("workflow.hierarchy-test-workflow.batch.1"),
      );
      const stepSpanCall = spanCalls.find(([name]: [string]) =>
        name.includes("workflow.hierarchy-test-workflow.step.parentStep"),
      );

      expect(workflowSpanCall).toBeDefined();
      expect(batchSpanCall).toBeDefined();
      expect(stepSpanCall).toBeDefined();

      // Each span should have end() called
      expect(spans.length).toBeGreaterThanOrEqual(3); // workflow + batch + step
      for (const span of spans) {
        expect(span.end).toHaveBeenCalled();
      }
      mockTracer.startSpan.mockImplementation(() => createMockSpan());
    });
  });

  describe("Async Step Observability", () => {
    it("should handle observability correctly for async steps", async () => {
      vi.useFakeTimers();
      try {
        const asyncStep = createTestStep("asyncStep", ["input"], ["processed"], async (bag) => {
          // Simulate async work
          await new Promise((resolve) => setTimeout(resolve, 10));
          return { processed: bag.input.toUpperCase() };
        });

        const workflow = createWorkflow<TestBag>("async-workflow")
          .requires("input")
          .build([asyncStep]);

        const workflowPromise = composerWithMockLogger.runSyncWorkflow(workflow, {
          input: "async",
        });
        await vi.runAllTimersAsync();
        const { bag } = await workflowPromise;

        // Verify async execution succeeded
        expect(bag).toEqual({ input: "async", processed: "ASYNC" });

        // Verify observability works the same for async steps
        expect(mockTracer.startSpan).toHaveBeenCalledWith(
          "workflow.async-workflow.step.asyncStep",
          expect.any(Object),
          expect.anything(), // Context parameter
        );

        expect(mockLogger.info).toHaveBeenCalledWith(
          "Workflow completed successfully",
          expect.objectContaining({
            workflowName: "async-workflow",
          }),
        );
      } finally {
        vi.useRealTimers();
      }
    });

    it("should handle mixed sync and async steps in same workflow", async () => {
      vi.useFakeTimers();
      try {
        const syncStep = createTestStep("syncStep", ["input"], ["processed"], (bag) => ({
          processed: bag.input.toUpperCase(),
        }));

        const asyncStep = createTestStep("asyncStep", ["processed"], ["result"], async (bag) => {
          await new Promise((resolve) => setTimeout(resolve, 5));
          return { result: `async-${bag.processed}` };
        });

        const workflow = createWorkflow<TestBag>("mixed-workflow")
          .requires("input")
          .build([syncStep, asyncStep]);

        const workflowPromise = composerWithMockLogger.runSyncWorkflow(workflow, {
          input: "mixed",
        });
        await vi.runAllTimersAsync();
        const { bag } = await workflowPromise;

        // Verify mixed execution succeeded
        expect(bag).toEqual({
          input: "mixed",
          processed: "MIXED",
          result: "async-MIXED",
        });

        // Verify both steps are traced
        expect(mockTracer.startSpan).toHaveBeenCalledWith(
          "workflow.mixed-workflow.step.syncStep",
          expect.any(Object),
          expect.anything(), // Context parameter
        );
        expect(mockTracer.startSpan).toHaveBeenCalledWith(
          "workflow.mixed-workflow.step.asyncStep",
          expect.any(Object),
          expect.anything(), // Context parameter
        );

        // Verify success log
        expect(mockLogger.info).toHaveBeenCalledWith(
          "Workflow completed successfully",
          expect.objectContaining({
            workflowName: "mixed-workflow",
            batchCount: 2,
          }),
        );
      } finally {
        vi.useRealTimers();
      }
    });
  });

  describe("Real-World Workflow Patterns", () => {
    it("should handle fan-out then fan-in pattern with complete observability", async () => {
      // Fan-out: one step produces data for multiple parallel steps
      const producer = createTestStep("producer", ["input"], ["processed"], (bag) => ({
        processed: bag.input.toUpperCase(),
      }));

      const consumer1 = createTestStep("consumer1", ["processed"], ["doubled"], (bag) => ({
        doubled: `${bag.processed}-doubled`,
      }));

      const consumer2 = createTestStep("consumer2", ["processed"], ["count"], (bag) => ({
        count: bag.processed.length,
      }));

      // Fan-in: one step consumes data from multiple parallel steps
      const aggregator = createTestStep("aggregator", ["doubled", "count"], ["result"], (bag) => ({
        result: `${bag.doubled}+${bag.count}`,
      }));

      const workflow = createWorkflow<TestBag>("fan-out-fan-in-workflow")
        .requires("input")
        .build([producer, consumer1, consumer2, aggregator]);

      const { bag } = await composerWithMockLogger.runSyncWorkflow(workflow, { input: "test" });

      // Verify complex workflow execution
      expect(bag).toEqual({
        input: "test",
        processed: "TEST",
        doubled: "TEST-doubled",
        count: 4,
        result: "TEST-doubled+4",
      });

      // Verify batch structure: [producer] -> [consumer1, consumer2] -> [aggregator]
      expect(mockTracer.startSpan).toHaveBeenCalledWith(
        "workflow.fan-out-fan-in-workflow.batch.1",
        expect.objectContaining({
          attributes: expect.objectContaining({
            "workflow.batch.steps.names": "producer",
          }),
        }),
        expect.anything(), // Context parameter
      );

      expect(mockTracer.startSpan).toHaveBeenCalledWith(
        "workflow.fan-out-fan-in-workflow.batch.2",
        expect.objectContaining({
          attributes: expect.objectContaining({
            "workflow.batch.steps.count": 2,
          }),
        }),
        expect.anything(), // Context parameter
      );

      expect(mockTracer.startSpan).toHaveBeenCalledWith(
        "workflow.fan-out-fan-in-workflow.batch.3",
        expect.objectContaining({
          attributes: expect.objectContaining({
            "workflow.batch.steps.names": "aggregator",
          }),
        }),
        expect.anything(), // Context parameter
      );

      // Verify success with correct batch count
      expect(mockLogger.info).toHaveBeenCalledWith(
        "Workflow completed successfully",
        expect.objectContaining({
          batchCount: 3,
          outputFields: expect.arrayContaining([
            "input",
            "processed",
            "doubled",
            "count",
            "result",
          ]),
        }),
      );
    });
  });
});
